Projeto-Tatuou/Models/Estilos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Estilos
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string Nome { get; set; }

        [Required]
        [MaxLength(255)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
        public Boolean Status { get; set; }

        public virtual ICollection<EstudioEstilo> EstudioEstilo { get; set; }
        [MaxLength(100)]
        public string Foto { get; set; }

    }
}

Projeto-Tatuou/Controllers/EstilosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace Projeto_Tatuou.Controllers
{

    public class EstilosController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Estilos
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Estilos.ToList());
        }

        [AllowAnonymous]
        public ActionResult Estilos()
        {
            return View(db.Estilos.Where(p => p.Status == true).OrderBy(p => p.Nome).ToList());
        }

        // GET: Estilos/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Estilos/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Descricao,Status")] Estilos estilos, HttpPostedFileBase arquivo)
        {
            string valor = "";
            if (ModelState.IsValid)
            {
                db.Estilos.Add(estilos);
                db.SaveChanges();
                if (arquivo != null)
                {
                    string nomearq = estilos.Nome.ToLower() + ".png";
                    valor = Funcoes.UploadEstilos(arquivo, nomearq);
                    if (valor == "sucesso")
                    {
                        estilos.Foto = nomearq;
                        db.Entry(estilos).State = EntityState.Modified;
                        db.SaveChanges();
                        TempData["MSG"] = "success|Estilo cadastrado com sucesso";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        System.IO.File.Copy(Request.PhysicalApplicationPath + "images\\user.png", Request.PhysicalApplicationPath + "images\\estilos\\" + estilos.Id + estilos.Nome + ".png");
                        estilos.Foto = estilos.Id + estilos.Nome + ".png";
                        db.Entry(estilos).State = EntityState.Modified;
                        db.SaveChanges();
                        TempData["MSG"] = "warning|Problema no Upload da foto: " + valor;
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    System.IO.File.Copy(Request.PhysicalApplicationPath + "images\\user.png", Request.PhysicalApplicationPath + "images\\estilos\\" + estilos.Id + estilos.Nome + ".png");
                    estilos.Foto = estilos.Id + estilos.Nome + ".png";
                    db.Entry(estilos).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["MSG"] = "success|Usuário cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }
        // GET: Estilos/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estilos estilos = db.Estilos.Find(id);
            if (estilos == null)
            {
                return HttpNotFound();
            }
            return View(estilos);
        }

        // POST: Estilos/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome, Descricao,Status")] Estilos estilos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estilos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estilos);
        }

        // GET: Estilos/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estilos estilos = db.Estilos.Find(id);
            if (estilos == null)
            {
                return HttpNotFound();
            }
            return View(estilos);
        }

        // POST: Estilos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estilos estilos = db.Estilos.Find(id);
            db.Estilos.Remove(estilos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projeto-Tatuou/Controllers/HomeController.cs
using WebApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Data.Entity;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private Contexto db = new Contexto();

        //[Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Estilos.Where(p => p.Status == true).OrderBy(p => p.Nome).ToList());
        }

        [AllowAnonymous]
        public ActionResult Cadastro()
        {
            if (User.Identity.IsAuthenticated == true)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastro(Cadastro cad)
        {
            if (ModelState.IsValid)
            {
                if (db.Usuario.Where(x => x.Email == cad.Email).ToList().Count > 0)
                {
                    TempData["MSG"] = "warning|E-mail já utilizado";
                    return RedirectToAction("Cadastro");
                }

                if(db.Usuario.Where(x => x.Cpf == cad.Cpf).ToList().Count > 0)
                {
                    TempData["MSG"] = "warning|CPF já utilizado";
                    return RedirectToAction("Cadastro");
                }
                Usuario usu = new Usuario();
                usu.Nome = cad.Nome;
                usu.Email = cad.Email;
                usu.Senha = Funcoes.HashTexto(cad.Senha, "SHA512");

                string num = cad.Cpf.Trim().Replace(".", "").Replace("-", "");
                int[] result = new int[num.Length];
                int soma;
                for (int i = 0; i < num.Length; i++)
                {
                    result[i] = (num[i] + 2) / 1 % 10;
                }

                soma = 0;

                soma += result[0] * 10;
                soma += result[1] * 9;
                soma += result[2] * 8;
                soma += result[3] * 7;
                soma += result[4] * 6;
                soma += result[5] * 5;
                soma += result[6] * 4;
                soma += result[7] * 3;
                soma += result[8] * 2;

                soma = (soma * 10) % 11;
                if (soma == 10 || soma == 11)
                {
                    soma = 0;
                }
                if (soma != result[9])
                {
                    TempData["MSG"] = "warning|CPF Inválido!";
                    RedirectToAction("Cadastro");
                }
                soma = 0;
                soma += result[0] * 11;
                soma += result[1] * 10;
                soma += result[2] * 9;
                soma += result[3] * 8;
                soma += result[4] * 7;
                soma += result[5] * 6;
                soma += result[6] * 5;
                soma += result[7] * 4;
                soma += result[8] * 3;
                soma += result[9] * 2;

                soma = (soma * 10) % 11;

                if (soma == 10 || soma == 11)
                {
                    soma = 0;
                }
                if (soma != result[10])
                {
                    TempData["MSG"] = "warning|CPF Inválido!";
                    return RedirectToAction("Cadastro");
                }
                else
                {
                    usu.Cpf = cad.Cpf;
                }
                usu.Status = true;
                usu.Perfil = db.Perfil.Find(2);
                if (usu.Perfil == null)
                {
                    ModelState.AddModelError("", "Não existe o perfil para cadastro");
                    return View(cad);
                }
                db.Usuario.Add(usu);
                db.SaveChanges();
                TempData["MSG"] = "success|Usuário Cadastrado com Sucesso";
                return RedirectToAction("Cadastro", "Estudios");
            }
            return View(cad);
        }

        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated == true)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Acesso acesso)
        {
            if (ModelState.IsValid)
            {
                string senhacrip = Funcoes.HashTexto(acesso.Senha, "SHA512");
                Usuario usu = db.Usuario.Where(x => x.Email == acesso.Email && x.Senha == senhacrip).ToList().FirstOrDefault();
                if (usu != null)
                {
                    FormsAuthentication.SetAuthCookie(usu.Id + "|" + usu.Nome, true);
                    string permissoes = usu.Perfil.Descricao;
                    FormsAuthenticationTicket ticket = new
                    FormsAuthenticationTicket(1, usu.Id + "|" + usu.Email + "|" + usu.PerfilId,
                    DateTime.Now, DateTime.Now.AddMinutes(30), true, permissoes);
                    string hash = FormsAuthentication.Encrypt(ticket);
                    HttpCookie cookie = new
                    HttpCookie(FormsAuthentication.FormsCookieName, hash);
                    Response.Cookies.Add(cookie);
                    Estudio estudio = db.Estudio.Where(p => p.UsuarioId == usu.Id).ToList().FirstOrDefault();
                    if (usu.Perfil.Descricao == "Admin")
                    {
                        return RedirectToAction("Estudios", "Estudios");
                    }
                    else
                    {
                        if (estudio != null)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return RedirectToAction("Cadastro", "Estudios");
                        }
                    }
                }
                else
                {
                    TempData["MSG"] = "error|E-mail e/ou Senha inválidos ou não encontrados";
                    return View(acesso);
                }
            }
            return View(acesso);
        }

        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }

        public ActionResult EsqueceuSenha()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EsqueceuSenha(EsqueceuSenha esq)
        {
            if (ModelState.IsValid)
            {
                var usu = db.Usuario.Where(x => x.Email == esq.Email).ToList().FirstOrDefault();
                if (usu != null)
                {
                    usu.Hash = Funcoes.Codifica(DateTime.Now.AddDays(1).ToString("yyyy-MM-dd HH:mm:ss.ffff"));
                    db.Entry(usu).State = EntityState.Modified;
                    db.SaveChanges();
                    string msg = "<h3>Sistema</h3>";
                    msg += "Para alterar sua senha <a href='http://localhost:26786/Home/Redefinir/" + usu.Hash + "' target='_blank'>clique aqui</a>";
                    TempData["MSG"] = Funcoes.EnviarEmail(usu.Email, "Redefinição de senha", msg);
                    return RedirectToAction("Index");
                }
                TempData["MSG"] = "error|E-mail não encontrado";
                return View();
            }
            TempData["MSG"] = "warning|Preencha todos os campos";
            return View();
        }

        public ActionResult Redefinir(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var usu = db.Usuario.Where(x => x.Hash == id).ToList().FirstOrDefault();
                if (usu != null)
                {
                    try
                    {
                        DateTime dt = Convert.ToDateTime(Funcoes.Decodifica(usu.Hash));
                        if (dt > DateTime.Now)
                        {
                            RedefinirSenha red = new RedefinirSenha();
                            red.Hash = usu.Hash;
                            red.Email = usu.Email;
                            return View(red);
                        }
                        TempData["MSG"] = "warning|Esse link já expirou!";
                        return RedirectToAction("Index");
                    }
                    catch
                    {
                        TempData["MSG"] = "error|Hash inválida!";
                        return RedirectToAction("Index");
                    }
                }
                TempData["MSG"] = "error|Hash inválida!";
                return RedirectToAction("Index");
            }
            TempData["MSG"] = "error|Acesso inválido!";
            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Redefinir(RedefinirSenha red)
        {
            if (ModelState.IsValid)
            {
                var usu = db.Usuario.Where(x => x.Hash == red.Hash).ToList().FirstOrDefault();
                if (usu != null)
                {
                    usu.Hash = null;
                    usu.Senha = Funcoes.HashTexto(red.Senha, "SHA512");
                    db.Entry(usu).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["MSG"] = "success|Senha redefinida com sucesso!";
                    return RedirectToAction("Index");
                }
                TempData["MSG"] = "error|E-mail não encontrado";
                return View(red);
            }
            TempData["MSG"] = "warning|Preencha todos os campos";
            return View(red);
        }
    }
}

Projeto-Tatuou/Views/Estilos/Create.cshtml
@model WebApplication1.Models.Estilos

@{
    ViewBag.Title = "Create";
}

<section class="section cta dark">
    <div class="container" style="margin-top: 7rem;">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                @using (Html.BeginForm("Create", "Estilos", FormMethod.Post, new
                {
                    enctype = "multipart/form-data"
                }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h3 class="mb-5 text-center display-4"><strong>Cadastro de Estilos</strong></h3>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="form-outline col-md-6 offset-md-3 mb-4">
                                <img src="~/images/camera.png" alt="Selecione uma imagem" id="imgStyle" />
                                <label>Foto de Perfil</label>
                                <input id="style-input" name="arquivo" type="file" />
                            </div>
                            <script>
                                'use strict'

                                var photo = document.getElementById('imgStyle');
                                var file = document.getElementById('style-input');

                                photo.addEventListener('click', () => {
                                    file.click();
                                })

                                file.addEventListener('change', () => {

                                    if (file.files.length <= 0) {
                                        return;
                                    }

                                    var reader = new FileReader();

                                    reader.onload = () => {
                                        photo.src = reader.result;
                                    }

                                    reader.readAsDataURL(file.files[0]);
                                });
                            </script>
                            <div class="form-outline col-md-4 col-sm-12 mb-4">
                                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label text-left" })
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-outline col-md-8 col-sm-12 mb-4">
                                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label text-left" })
                                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-outline col-md-12 col-sm-12 mb-4">
                                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label text-left" })
                                <select name="status" class="select-btn">
                                    <option value="true">Ativo</option>
                                    <option value="false">Inativo</option>
                                </select>
                            </div>


                            <div class="form-outline col-md-12">
                                <input type="submit" value="Cadastrar" class="btn btn-block" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projeto-Tatuou/Views/Estilos/Delete.cshtml
@model WebApplication1.Models.Estilos

@{
    ViewBag.Title = "Delete";
}

<section class="section cta dark">
    <div class="container text-left" style="margin-top: 5rem;">
        <h2 class="mb-5 text-center">
            <strong>
                Tem certeza que deseja excluir este estilo?
            </strong>
        </h2>
        <div class="form-horizontal">
            <div class="row">
                <div class="form-outline col-md-4 col-sm-12">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @disabled = "disable" } })
                </div>
                <div class="form-outline col-md-8 col-sm-12">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", @disabled = "disable" } })
                </div>
            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <input type="submit" value="Sim" class="btn btn-block" />
            <a href="@Url.Action("Index")" class="btn">Voltar</a>
        }
    </div>

</section>

Projeto-Tatuou/Views/Estilos/Edit.cshtml
@model WebApplication1.Models.Estilos

@{
    ViewBag.Title = "Edit";
}
<section class="section cta dark">
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h3 class="mb-5 text-center display-4">Editar</h3>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        <div class="row">
                            <div class="form-outline col-6">
                                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label text-left" })
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-outline col-6">
                                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label text-left" })
                                <select name="Status" class="select-btn">
                                    <option value="true" selected>Ativo</option>
                                    <option value="false">Inativo</option>
                                </select>
                            </div>
                            <div class="form-outline col-12">
                                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label text-left" })
                                @Html.TextAreaFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", @rows = "5", @cols = "30" } })
                                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                            </div>
                            <div class="fomr-outline col-6">
                                <a href="@Url.Action("Index")" class="btn btn-block">Voltar</a>
                            </div>

                            <div class="form-outline col-6">
                                <input type="submit" value="Salvar" class="btn btn-block" />
                            </div>
                        </div>

                    </div>
                }
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projeto-Tatuou/Views/Estilos/Estilos.cshtml
@model IEnumerable<WebApplication1.Models.Estilos>

@{
    ViewBag.Title = "Estilos";
}
<section class="section cta dark">
    <div class="content container my-5 py-5">
        <div class="work">
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="work col-md-4 col-sm-6">

                        <div class="work-thumb">
                            <h5>@Html.DisplayFor(modelItem => item.Nome)</h5>
                            <img src="~/images/estilos/@Html.DisplayFor(modelItem => item.Foto)" alt="@Html.DisplayFor(modelItem => item.Nome)">
                            <div class="thumb-links">
                                <a class="zoom" href="~/images/estilos/@Html.DisplayFor(modelItem => item.Foto)"></a>
                            </div>
                            <h6>@Html.DisplayFor(modelItem => item.Descricao)</h6>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

Projeto-Tatuou/Views/Estilos/Home.cshtml
@model WebApplication1.Models.EstudioEstilo


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EstudioEstilo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.estudioId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estudioId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estudioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estilosId, "estilosId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("estilosId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.estilosId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projeto-Tatuou/Views/Estilos/Index.cshtml
@model IEnumerable<WebApplication1.Models.Estilos>

@{
    ViewBag.Title = "Index";
}

<section class="section cta dark">
    <div class="container" style="margin-top: 5rem;">
        <div class="row">
            <div class="col-md-12">
                <div class="card py-5 px-5 text-center">
                    <h4 class="display-4" style="color:black;">Listagem de Estilos</h4>
                    <a href="@Url.Action("Create","Estilos")"class="col-md-6 offset-md-3 btn btn-block mt-3">Cadastrar Estilos</a>
                    <table class="table table-striped table-responsive">
                        <thead>
                            <tr>
                                <th width="30%">
                                    Nome
                                </th>
                                <th width="10%">
                                    Disponível
                                </th>
                                <th width="30%">
                                    Ações
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nome)
                                    </td>
                                    <td>
                                        @if (item.Status == false)
                                        {
                                            ViewBag.Disponivel = "Não";
                                        }
                                        else
                                        {
                                            ViewBag.Disponivel = "Sim";
                                        }
                                        @ViewBag.Disponivel
                                    </td>
                                    <td class="text-center">
                                        <a href="@Url.Action("Edit", "Estilos", new { id = item.Id })"><i class="bi bi-pencil-square" style="font-size: 1.5em !important; color: black !important;"></i></a>
                                        <a href="@Url.Action("Delete", "Estilos", new { id = item.Id })"><i class="bi bi-trash" style="font-size: 1.5em !important; color: black !important;"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>